[package]
name = "agb_sound_converter"
version = "0.1.0"
authors = ["Gwilym Kuiper <gw@ilym.me>"]
edition = "2018"
license = "MPL-2.0"
description = "Library for converting wavs for use on the Game Boy Advance"

[profile.dev]
opt-level = 3
debug = true

[profile.release]
lto = true
debug = true

[lib]
proc-macro = true

[features]
freq18157 = []

[dependencies]
hound = "3.4.0"
syn = "1.0.84"
proc-macro2 = "1.0.36"
quote = "1.0.14"
siphasher = "0.3.7"