[package]
name = "agb_template"
version = "0.1.0"
authors = [""]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agb = "0.9.2"

[dev-dependencies]
agb = { version = "0.9.2", features = ["testing"] }

[profile.release]
panic = "abort"
lto = true