[package]
name = "agb_xm"
version = "0.20.1"
authors = ["Gwilym Inzani <gw@ilym.me>"]
edition = "2021"
license = "MPL-2.0"
description = "Library for converting XM tracker files for use with agb-tracker on the Game Boy Advance. You shouldn't use this package directly"
repository = "https://github.com/agbrs/agb"

[lib]
proc-macro = true

[dependencies]
agb_xm_core = { version = "0.20.1", path = "../agb-xm-core" }
proc-macro-error = "1"
proc-macro2 = "1"
