[package]
name = "mgba"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.153"
mgba-sys = { version = "0.1.0", path = "../mgba-sys" }
thiserror = "1"