[package]
name = "agb_macros"
version = "0.1.0"
authors = ["Gwilym Kuiper <gw@ilym.me>"]
edition = "2018"
license = "MPL-2.0"
description = "Macro for declaring the entry point for a game using the agb library"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.86", features = ["full", "extra-traits"] }
proc-macro2 = "1.0.36"
quote = "1.0.15"
rand = "0.8.5"