[package]
name = "tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4"
toml_edit = "0.19"
glob = "0.3"
chrono = "0.4"
dependency-graph = "0.1.5"
