name: Publish agb-fixnum

on:
  push:
    tags:
      - agb-fixnum/v*

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install build-essential binutils-arm-none-eabi -y
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Login to crates.io
        run: cargo login ${{ secrets.CRATE_API }}
      - name: Publish agb-fixnum
        run: cargo publish
        working-directory: ./agb-fixnum